data = [
    'addx 15',
    'addx -11',
    'addx 6',
    'addx -3',
    'addx 5',
    'addx -1',
    'addx -8',
    'addx 13',
    'addx 4',
    'noop',
    'addx -1',
    'addx 5',
    'addx -1',
    'addx 5',
    'addx -1',
    'addx 5',
    'addx -1',
    'addx 5',
    'addx -1',
    'addx -35',
    'addx 1',
    'addx 24',
    'addx -19',
    'addx 1',
    'addx 16',
    'addx -11',
    'noop',
    'noop',
    'addx 21',
    'addx -15',
    'noop',
    'noop',
    'addx -3',
    'addx 9',
    'addx 1',
    'addx -3',
    'addx 8',
    'addx 1',
    'addx 5',
    'noop',
    'noop',
    'noop',
    'noop',
    'noop',
    'addx -36',
    'noop',
    'addx 1',
    'addx 7',
    'noop',
    'noop',
    'noop',
    'addx 2',
    'addx 6',
    'noop',
    'noop',
    'noop',
    'noop',
    'noop',
    'addx 1',
    'noop',
    'noop',
    'addx 7',
    'addx 1',
    'noop',
    'addx -13',
    'addx 13',
    'addx 7',
    'noop',
    'addx 1',
    'addx -33',
    'noop',
    'noop',
    'noop',
    'addx 2',
    'noop',
    'noop',
    'noop',
    'addx 8',
    'noop',
    'addx -1',
    'addx 2',
    'addx 1',
    'noop',
    'addx 17',
    'addx -9',
    'addx 1',
    'addx 1',
    'addx -3',
    'addx 11',
    'noop',
    'noop',
    'addx 1',
    'noop',
    'addx 1',
    'noop',
    'noop',
    'addx -13',
    'addx -19',
    'addx 1',
    'addx 3',
    'addx 26',
    'addx -30',
    'addx 12',
    'addx -1',
    'addx 3',
    'addx 1',
    'noop',
    'noop',
    'noop',
    'addx -9',
    'addx 18',
    'addx 1',
    'addx 2',
    'noop',
    'noop',
    'addx 9',
    'noop',
    'noop',
    'noop',
    'addx -1',
    'addx 2',
    'addx -37',
    'addx 1',
    'addx 3',
    'noop',
    'addx 15',
    'addx -21',
    'addx 22',
    'addx -6',
    'addx 1',
    'noop',
    'addx 2',
    'addx 1',
    'noop',
    'addx -10',
    'noop',
    'noop',
    'addx 20',
    'addx 1',
    'addx 2',
    'addx 2',
    'addx -6',
    'addx -11',
    'noop',
    'noop',
    'noop',
]
data = [
    'addx 1',
    'addx 4',
    'addx -2',
    'addx 3',
    'addx 3',
    'addx 1',
    'noop',
    'addx 5',
    'noop',
    'noop',
    'noop',
    'addx 5',
    'addx 2',
    'addx 3',
    'noop',
    'addx 2',
    'addx 4',
    'noop',
    'addx -1',
    'noop',
    'addx 3',
    'addx -10',
    'addx -17',
    'noop',
    'addx -3',
    'addx 2',
    'addx 25',
    'addx -24',
    'addx 2',
    'addx 5',
    'addx 2',
    'addx 3',
    'noop',
    'addx 2',
    'addx 14',
    'addx -9',
    'noop',
    'addx 5',
    'noop',
    'noop',
    'addx -2',
    'addx 5',
    'addx 2',
    'addx -5',
    'noop',
    'noop',
    'addx -19',
    'addx -11',
    'addx 5',
    'addx 3',
    'noop',
    'addx 2',
    'addx 3',
    'addx -2',
    'addx 2',
    'noop',
    'addx 3',
    'addx 4',
    'noop',
    'noop',
    'addx 5',
    'noop',
    'noop',
    'noop',
    'addx 5',
    'addx -3',
    'addx 8',
    'noop',
    'addx -15',
    'noop',
    'addx -12',
    'addx -9',
    'noop',
    'addx 6',
    'addx 7',
    'addx -6',
    'addx 4',
    'noop',
    'noop',
    'noop',
    'addx 4',
    'addx 1',
    'addx 5',
    'addx -11',
    'addx 29',
    'addx -15',
    'noop',
    'addx -12',
    'addx 17',
    'addx 7',
    'noop',
    'noop',
    'addx -32',
    'addx 3',
    'addx -8',
    'addx 7',
    'noop',
    'addx -2',
    'addx 5',
    'addx 2',
    'addx 6',
    'addx -8',
    'addx 5',
    'addx 2',
    'addx 5',
    'addx 17',
    'addx -12',
    'addx -2',
    'noop',
    'noop',
    'addx 7',
    'addx 9',
    'addx -8',
    'addx 2',
    'addx -33',
    'addx -1',
    'addx 2',
    'noop',
    'addx 26',
    'addx -22',
    'addx 19',
    'addx -16',
    'addx 8',
    'addx -1',
    'addx 3',
    'addx -2',
    'addx 2',
    'addx -17',
    'addx 24',
    'addx 1',
    'noop',
    'addx 5',
    'addx -1',
    'noop',
    'addx 5',
    'noop',
    'noop',
    'addx 1',
    'noop',
    'noop',
]

counter = 0
adding = False
adding_value = 0
signals = {}
sprite = (0, 1, 2)
while True:
    # if counter in (20, 60, 100, 140, 180, 220):
    #     signals[counter] = value
    if counter in sprite:
        print('#', end='')
    else:
        print(' ', end='')
    if adding:
        adding = False
        value = sprite[1] + adding_value
        sprite = (value - 1, value, value + 1)
        counter += 1
        if counter == 40:
            print()
            counter = 0
        continue
    try:
        instruction = data.pop(0)
    except IndexError:
        break
    if instruction == 'noop':
        pass
    else:
        instruction, v = instruction.split()
        adding_value = int(v)
        adding = True
    counter += 1
    if counter == 40:
        print()
        counter = 0


# print(sum(k * v for k, v in signals.items()))
